bare/lead/uupload: auto-select first ttyACM (optional)

diff --git a/bare/lead/uupload b/bare/lead/uupload
--- a/bare/lead/uupload
+++ b/bare/lead/uupload
@@ -4,7 +4,7 @@
 
 usage()
 {
-	echo "usage: $0 tty file" 1>&2
+	echo "usage: $0 [tty] file" 1>&2
 	exit 1
 }
 
@@ -16,20 +16,31 @@ while [ "$1" ]; do
 	esac
 done
 
-[ "$2" ] || usage
+[ "$1" ] || usage
 [ "$3" ] && usage
 
-if [ -c "$1" ]; then
-	tty=$1
-elif [ -c /dev/tty"$1" ]; then
-	tty=/dev/tty$1
+if [ "$2" ]; then
+	if [ -c "$1" ]; then
+		tty=$1
+	elif [ -c /dev/tty"$1" ]; then
+		tty=/dev/tty$1
+	else
+		echo "$1: not a tty" 1>&2
+		exit 1
+	fi
+	shift
 else
-	echo "$1: not a tty" 1>&2
-	exit 1
+	tty=/dev/ttyACM`ls -1 /dev/ttyACM* | sed 's/.*ttyACM'// |
+	    sort -n | sed 1q`
+	if [ ! -c "$tty" ]; then
+		echo "no suitable tty found" 1>&2
+		exit 1
+	fi
 fi
 
-if [ ! -f "$2" ]; then
-	echo "$2: not found" 1>&2
+
+if [ ! -f "$1" ]; then
+	echo "$1: not found" 1>&2
 	exit 1
 fi
 
@@ -38,6 +49,6 @@ fi
 	sleep 0.1
 	echo uudecode
 	# slow down so that we don't overrun anything
-	uuencode "$2" "$2" | while read -r l; do echo "$l"; sleep 0.01; done
+	uuencode "$1" "$1" | while read -r l; do echo "$l"; sleep 0.01; done
 	echo stty echo
 ) >"$tty"
